"""
games/ethology/codegen.py
--------------------------
Pure code generation — no pygame, no UI.
Imported by both hierarchy_builder.py and game.py.
"""

import datetime

# All behaviors available in the pool
BEHAVIORS = [
    ("Escape Front",    "escape_front",    False),
    ("Escape Rear",     "escape_rear",     False),
    ("Avoid Object",    "avoid_object",    False),
    ("Approach Object", "approach_object", False),
    ("Seek Light",      "seek_light",      True),
    ("Avoid Light",     "avoid_light",     True),
    ("Cruise Straight", "cruise_straight", False),
    ("Cruise Arc",      "cruise_arc",      False),
]

BEHAVIOR_MAP  = {b[1]: b for b in BEHAVIORS}

BEHAVIOR_CODE = {
    "escape_front":    ("front_contact_met()",     "escape_front()"),
    "escape_rear":     ("rear_contact_met()",      "escape_rear()"),
    "avoid_object":    ("proximity_threshold_met()","avoid_object()"),
    "approach_object": ("proximity_threshold_met()","approach_object()"),
    "seek_light":      ("light_gradient_met()",    "seek_light()"),
    "avoid_light":     ("light_gradient_met()",    "avoid_light()"),
    "cruise_straight": ("true",                    "cruise_straight()"),
    "cruise_arc":      ("true",                    "cruise_arc()"),
}


def needs_light(hierarchy: list[str]) -> bool:
    return any(BEHAVIOR_MAP[k][2] for k in hierarchy)


def generate_sketch(hierarchy: list[str], sketch_name: str) -> str:
    use_light   = needs_light(hierarchy)
    robot_class = "LDREthologyRobot" if use_light else "EthologyRobot"
    robot_hdr   = "LDREthologyRobot.h" if use_light else "EthologyRobot.h"

    # Build hierarchy() body — if/else chain
    lines = []
    for i, key in enumerate(hierarchy):
        cond, action = BEHAVIOR_CODE[key]
        label = BEHAVIOR_MAP[key][0]
        if cond != "true":
            cond = f"bot.{cond}"
        if i == 0:
            lines.append(f"  if ({cond}) {{  // {label}")
        elif cond == "true":
            lines.append(f"  else {{  // {label}")
        else:
            lines.append(f"  else if ({cond}) {{  // {label}")
        lines.append(f"    bot.{action};")
        lines.append( "  }")

    hier_body = "\n".join(lines)
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    return f"""\
/*
  {sketch_name}
  Generated by RoboSim Hierarchy Builder — {ts}

  Hierarchy (highest priority first):
{chr(10).join(f"    {i+1}. {BEHAVIOR_MAP[k][0]}" for i, k in enumerate(hierarchy))}

  Architecture mirrors the physical robot:
    - {robot_class} provides individual behavior methods
    - hierarchy() chains them in priority order
    - loop() calls hierarchy() each tick
*/

#include <Servo.h>
#include "CogServo.h"
#include "{robot_hdr}"

CogServo driveServos;
{robot_class} bot(driveServos);

void hierarchy() {{
{hier_body}
}}

void setup() {{
  Serial.begin(9600);
  driveServos.begin(0, 1);
  bot.begin();
}}

void loop() {{
  hierarchy();
}}
"""
