/*
  target_A.ino
  Generated by RoboSim Hierarchy Builder — 2026-04-09 00:17

  Hierarchy (highest priority first):
    1. Escape Front
    2. Escape Rear
    3. Avoid Object
    4. Cruise Straight
*/

#include <Servo.h>
#include "CogServo.h"
#include "EthologyRobot.h"

CogServo driveServos;
EthologyRobot bot(driveServos);

void setup() {
  Serial.begin(9600);
  driveServos.begin(0, 1);
  bot.begin();
}

void loop() {
  if (bot.front_contact_met()) {  // Escape Front
    bot.escape_front();
  }
  else if (bot.rear_contact_met()) {  // Escape Rear
    bot.escape_rear();
  }
  else if (bot.proximity_threshold_met()) {  // Avoid Object
    bot.avoid_object();
  }
  else {  // Cruise Straight
    bot.cruise_straight();
  }
}
