/*
  target_B.ino
  Generated by RoboSim Hierarchy Builder — 2026-04-09 00:17

  Hierarchy (highest priority first):
    1. Approach Object
    2. Avoid Light
    3. Cruise Straight
*/

#include <Servo.h>
#include "CogServo.h"
#include "LDREthologyRobot.h"

CogServo driveServos;
LDREthologyRobot bot(driveServos);

void setup() {
  Serial.begin(9600);
  driveServos.begin(0, 1);
  bot.begin();
}

void loop() {
  if (bot.proximity_threshold_met()) {  // Approach Object
    bot.approach_object();
  }
  else if (bot.light_gradient_met()) {  // Avoid Light
    bot.avoid_light();
  }
  else {  // Cruise Straight
    bot.cruise_straight();
  }
}
