/*
  hypothesis_A_20260422_105925.ino
  Generated by RoboSim Hierarchy Builder — 2026-04-22 10:59

  Hierarchy (highest priority first):
    1. Escape Front

  Architecture mirrors the physical robot:
    - EthologyRobot provides individual behavior methods
    - hierarchy() chains them in priority order
    - loop() calls hierarchy() each tick
*/

#include <Servo.h>
#include "CogServo.h"
#include "EthologyRobot.h"

CogServo driveServos;
EthologyRobot bot(driveServos);

void hierarchy() {
  if (bot.front_contact_met()) {  // Escape Front
    bot.escape_front();
  }
}

void setup() {
  Serial.begin(9600);
  driveServos.begin(0, 1);
  bot.begin();
}

void loop() {
  hierarchy();
}
